### ISSUE TITLE
Regex Multiple File Matching not working (on Windows ?)

### ISSUE THREAD

**Issue by coumbsek** [zsiki/Find-GCP#3]
Hi,

I have tried the various examples with the provided samples like this one for instance :
`./gcp\_find.py -v -t ODM -i samples/A3.txt --epsg 23700 -o samples/gcp_list.txt --minrate 0.01 --ignore 0.33 -d 99 samples/DJI_017[234].JPG
`
But the regex make the file name unrecognised : 
`processing samples\DJI_017[234].JPG`
`error reading image: samples\DJI_017[234].JPG`

I have tried to read and analyse the code of the gcp_find.py but not being a fan of python, my lack of practice does not help...

When I try to debug :
`for f_name in self.args.names` line 147 in function process_images, the range of the for loop seems to be an array of a single element beeing "samples/DJI_017[234].JPG". I do not see in the code where the files are crossed to see which one match the regex or what should achieve this principle and fill the self.args.names array with a valid array of filenames.

Thank you in advance for your help

**Comment by zsiki** [comment]
The root of this issue is in the different wildcard handling of the operating systems. In case of Linux the shell (the command interpreter) extend the wildcards (e.g. *?[]) before to command starts, while on Windows the command should do it.
Another issue is that window doesn't handle [123] like wildcards.
So on Linux if you give the 

`echo samples/DJI_017[234].JPG`

You get

`samples/DJI_0172.JPG samples/DJI_0173.JPG samples/DJI_0174.JPG`

But on Windows you get:

`samples/DJI_017[234].JPG`

The quick solution is not ot use wildcards in the command line on Windows:

`./gcp\_find.py -v -t ODM -i samples/A3.txt --epsg 23700 -o samples/gcp_list.txt --minrate 0.01 --ignore 0.33 -d 99 samples/DJI_0172.JPG samples/DJI_0173.JPG samples/DJI_0174.JPG `

The other solution is to use the `glob` library of Python to extend wildcards. We have to change the code...

**Comment by coumbsek** [comment]
Thank you for confirming what I was thinking.

During my research I had a look had the glob lib.

I will first pass all the file name with a script as command line arguments and later will examine how to use glob and if I managed to do something make a pull request.

Thank you

**Comment by zsiki** [comment]
I added the necessary code, please test it.

**Comment by coumbsek** [comment]
Nicer than what I did event if it is now platform dependant.

Almost working. In order to make it work I had to add the "import glob" at the beginning of the file.

**Comment by zsiki** [comment]
Thanks for your response, I've added `import glob`.
